### ISSUE TITLE
Reviews of your design doc

### ISSUE THREAD

**Issue by aracpyon** [omelnykov1/tonightbnb#1]
Hey Alex, here are my reviews on what you have so far

- [x] please make wiki page for both `MVPs` and `Schema`
- [x] Please submit your `Schema`
- [x] Please follow the MVPs as follows: 

1. Spots
2. Bookings
3. Spots search (by location & availability) & Google Maps on search
4. Reviews
Bonus: Messaging
Bonus: User/host profiles

**MVPs**
- [x] Add `Bookings` as your 4th MVP 
- [x] move Google Map functionality from `listings` to `Search` MVP. 
- [x] Should have `Booking functionality` before you start working on `Search.`

**Comment by aracpyon** [comment]
Hey Alex, great job on your schema and sample slate in a short period of time!
Here are my reviews on schema and state:

**schema**

- [ ] please add `longitude` and `latitude` columns to your `spots` table(will be useful for your search  and map MVP later)

**state**
your sample state looks great so far! Just one minor thing:
 - [ ] add `startDate` and `endDate` to your `booking state`. It will be useful later when you color the reserved days on your calendar.

**Comment by omelnykov1** [comment]
.
