### ISSUE TITLE
MVP #2 User authentication 

### ISSUE THREAD

**Issue by omelnykov1** [omelnykov1/tonightbnb#3]
Added login/signup/logout and demo user
Created main(splash) page

Hopefully that's all for auth.

**Comment by aracpyon** [comment]
Great job on your auth! Here are my reviews:

-[ ] get rid of the blue highlight around the input boxes
- [ ] Your clone has a nice animation effect on the input areas. Please do the same. (use this resource: [https://css-tricks.com/float-labels-css/](url)) 
![Screen Shot 2020-06-04 at 2 12 09 PM](https://user-images.githubusercontent.com/56740477/83795446-76066c80-a66d-11ea-8fc0-b67fc908a3f4.png)

- [ ] Please make your error messages similar to your clone
![Screen Shot 2020-06-04 at 2 11 01 PM](https://user-images.githubusercontent.com/56740477/83795322-4d7e7280-a66d-11ea-9b3e-2a75aa03cfc5.png)

**Comment by omelnykov1** [comment]
.
